### ISSUE TITLE
TempFolder fails to create on Linux

### ISSUE THREAD

**Issue by cornytrace** [Noggog/CSharpExt#3]
On Linux with net6.0 the following code from Mutagen fails to create the specified directory. Manually creating /tmp/Mutagen_Binary_Tests/ allows Mutagen to continue.
`var tmp = TempFolder.FactoryByPath(Path.Combine(Path.GetTempPath(), $"Mutagen_Binary_Tests/{Nickname}"), deleteAfter: Settings.DeleteCachesAfter);`

If you want to test this out yourself I have a branch called 'linux' on my fork of Mutagen that can compile on Linux.

**Comment by Noggog** [comment]
Is there a stack trace related to the failed creation?  Is it due to `Path.GetTempPath` not providing a valid location on the linux environments?

Also might just be the fact that I'm using `/` in the path rather than `Path.Combine` or something more environment generic

**Comment by cornytrace** [comment]
I have a fix on my "linux" branch but the formatting of vscode of all things is preventing me from making a PR. vscode or the omnisharp extension seems to automatically remove the indenting of empty lines, and there is no option to fix that yet...

**Comment by Noggog** [comment]
I think this was merged in with the pr? #4
